---
- import_tasks: install.yml
  when: customer_services.mailcow.enabled | default(false)

- import_tasks: initialize.yml
  when: customer_services.mailcow.enabled | default(false)

- import_tasks: configure.yml
  when: customer_services.mailcow.enabled | default(false)

- import_tasks: deploy.yml
  when: customer_services.mailcow.enabled | default(false)

- import_tasks: verify.yml
  when: customer_services.mailcow.enabled | default(false)
