---
mattermost_settings:
  container_name_suffix: mattermost
  uid: 2000
  gid: 2000

  port: 8065

  db:
    name: mattermost
    user: mmuser

  traefik:
    entrypoint: websecure
    certresolver: letsencrypt
