---
- name: Create Mattermost directories
  ansible.builtin.file:
    path: "{{ global_platform.data_root }}/{{ company.short_name }}/mattermost/{{ item }}"
    state: directory
    owner: "{{ mattermost_settings.uid }}"
    group: "{{ mattermost_settings.gid }}"
    mode: "0755"
  loop:
    - config
    - data
    - logs
    - plugins

- name: Set Mattermost directory permissions
  ansible.builtin.file:
    path: "{{ global_platform.data_root }}/{{ company.id }}/mattermost"
    recurse: true
    mode: "0775"
