---
- name: Install Platform Services
  hosts: company_servers
  become: true
  gather_facts: true

  pre_tasks:
    - name: Debug and inspect tenant service states
      ansible.builtin.debug:
        var: customer_services

  roles:
    - docker
    - traefik
    - postgres
    - mattermost
    - mailcow
