---
- name: Validate that customer Next.js deployment image specifications are populated
  ansible.builtin.assert:
    that:
      - github.owner is defined
      - github.owner | length > 0
      - company.short_name is defined
      - company.short_name | length > 0
      - customer_apps.nextjs.repository is defined
      - customer_apps.nextjs.repository | length > 0
      - customer_apps.nextjs.tag is defined
      - customer_apps.nextjs.tag | length > 0
      - customer_apps.nextjs.hostname is defined
      - customer_apps.nextjs.hostname | length > 0
    fail_msg: "FATAL ERROR: Customer Next.js target container image or hostname is unconfigured."
    success_msg: "Customer Next.js configuration profiles validated."
